import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Artbyparthi",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#F7C7CC" },
    { media: "(prefers-color-scheme: dark)", color: "#5C1A72" },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}  
      className="bg-charcoal text-blush"
      >
        {children}
        <Toaster position="bottom-right" reverseOrder={false} toastOptions={{ duration: 2000 }} limit={3}/>
      </body>
    </html>
  );
}
